# Generated by Django 5.1.6 on 2025-03-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('ice_zone', models.IntegerField(verbose_name='Район по гололеду')),
                ('wind_zone', models.IntegerField(verbose_name='Район по ветровому давлению')),
                ('avg_year_temp', models.FloatField(verbose_name='Среднегодовая температура')),
                ('min_temp', models.FloatField(verbose_name='Минимальная температура')),
                ('max_temp', models.FloatField(verbose_name='Максимальная температура')),
            ],
            options={
                'ordering': ['city'],
            },
        ),
    ]
