# Generated by Django 5.1.6 on 2025-05-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lep', '0003_alter_wiresinfo_mod_elast_mat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Субъект')),
                ('ice_zone', models.IntegerField(verbose_name='Район по гололеду')),
                ('wind_zone', models.IntegerField(verbose_name='Район по ветровому давлению')),
                ('avg_year_temp', models.FloatField(verbose_name='Среднегодовая температура')),
                ('min_temp', models.FloatField(verbose_name='Абсолютная минимальная температура')),
                ('max_temp', models.FloatField(verbose_name='Абсолютная максимальная температура')),
            ],
            options={
                'ordering': ['subject'],
            },
        ),
    ]
