# Generated by Django 5.1.6 on 2025-06-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lep', '0004_subjectinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityInfo',
        ),
    ]
